### ISSUE TITLE
Event attendee self-registration

### ISSUE THREAD

**Issue by aaronpowell** [microsoft/azure-openai-service-proxy#106]
An event attendee needs to be able to apply for an API key before they are able to use the proxy API.

With #75 mostly complete, we are able to generate new events for them to apply for in a self-service model.

To achieve this, there will be a new section in the Playground that they will register an account using GitHub (or other social providers that are supported by SWA), and then join the event that they are participating in. If they have previously registered, they will be able to login with their GitHub OAuth workflow and join the event.

Since the Playground is deployed to SWA with the Proxy being treated as the API endpoint, the new APIs to register attendees and add them to events will need to be added to the Proxy application.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/azure-openai-service-proxy/issues/107
- [ ] https://github.com/microsoft/azure-openai-service-proxy/issues/108
- [ ] https://github.com/microsoft/azure-openai-service-proxy/issues/109
- [ ] https://github.com/microsoft/azure-openai-service-proxy/issues/110
- [ ] https://github.com/microsoft/azure-openai-service-proxy/issues/111
- [ ] https://github.com/microsoft/azure-openai-service-proxy/issues/112
- [ ] https://github.com/microsoft/azure-openai-service-proxy/issues/128
```
