### ISSUE TITLE
Proxy enhancements

### ISSUE THREAD

**Issue by gloveboxes** [microsoft/azure-openai-service-proxy#275]
```[tasklist]
### Tasks
- [ ] Extend model support: Mistral, Llama, gpt-4-vision
- [ ] Support for Assistant API
- [ ] Performance: Move metric logging to [FastAPI Background Task](https://fastapi.tiangolo.com/tutorial/background-tasks/)
```
