### ISSUE TITLE
Playground enhancements

### ISSUE THREAD

**Issue by gloveboxes** [microsoft/azure-openai-service-proxy#276]
```[tasklist]
### Tasks
- [ ] Support for gpt-4-vision image upload
- [ ] Event page system generated event model listing
- [ ] Clean up Chat example and add embedding example to the event page
- [ ] Investigate playground exception for large payloads
```
