### ISSUE TITLE
Self-service admin for event organisers

### ISSUE THREAD

**Issue by aaronpowell** [microsoft/azure-openai-service-proxy#38]
Presently, when you want to add a new event, this requires going into the Azure resource group, accessing the Storage account and adding a new record to the table, or using one of the management REST APIs that are available (provided you have the appropriate access token).

There is also no easy way to revoke a token, add a new model to an event, or general administrative tasks.

This is tracking the overall feature request.

- [x] ~#40~ Replaced by #44
- [x] #39
- [x] ~#41~
- [x] #42
  - We can leverage [authN and authZ for Container Apps](https://learn.microsoft.com/azure/container-apps/authentication) for this
- [x] #43
- [x] #44
- [x] ~#45~ Replaced by #77

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/azure-openai-service-proxy/issues/75
- [ ] https://github.com/microsoft/azure-openai-service-proxy/issues/77
- [ ] https://github.com/microsoft/azure-openai-service-proxy/issues/86
```

**Comment by gloveboxes** [comment]
completed
