### ISSUE TITLE
Implement usage metric tracking

### ISSUE THREAD

**Issue by gloveboxes** [microsoft/azure-openai-service-proxy#84]
Proxy service logs model requests to storage queue

Azure Function listens on storage queue
- [ ] updates the metric table
- [ ] checks if daily usage is greater than event request cap, if so 
      - sets event_attendee daily_request_limit exceeded flag
      - write a msg to the daily unlock storage queue for the unlock azurer function to unlock at 00:00 UTC
 - [ ] Postgresql schema updates
      - Remove total request from event_attendee
      - add daily_request_limit to event_attendee
- [ ] Add metric table
      - PRIMARY KEY (user_id, event_id),
      - Index event
      - cascade delete from event table by event_id

**Comment by aaronpowell** [comment]
Made everything into tasks which can be turned into separate issues if desired.

Probably best to do this in a feature branch (and then build each piece on top of the late one) so that it's an easier merge.

**Comment by gloveboxes** [comment]
Done
